// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylnirtmzmegvlomwmpvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsbmlydG16bWVndmxvbXdtcHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTA2NTgsImV4cCI6MjA3MDEyNjY1OH0.PyfqIOwtb_RENYjvg2kSm_LpNhXjejruCvYmNi9ukzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});